language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

cache:
  apt: true

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^.*travis.*$/

env:
  matrix:
    - USE_LLVM=Off
    - USE_LLVM=On

before_install:
  - ./.travis/linux/install-dependencies.sh

before_script: cmake . -DUSE_LLVM=$USE_LLVM -DCMAKE_BUILD_TYPE=Release

script: make

