language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

cache:
  apt: true

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^.*travis.*$/

env:
  matrix: # fix all scripts (e.g. install-dependencies.sh) if you rename LLVM_USE[On/Off]
    - USE_LLVM=Off
      BUILD_TYPE=Debug
    - USE_LLVM=Off
      BUILD_TYPE=Release
    - USE_LLVM=On
      BUILD_TYPE=Debug
    - USE_LLVM=On
      BUILD_TYPE=Release

before_install:
  - ./.travis/${TRAVIS_OS_NAME}/install-dependencies.sh

before_script:
  - mkdir -p build
  - cd build
  - cmake .. -DUSE_LLVM=$USE_LLVM -DBUILD_TESTS=On -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSITE="${TRAVIS_OS_NAME}@Travis" -DBUILDNAME="${TRAVIS_BRANCH}_${CXX}_LLVM_${USE_LLVM}_${BUILD_TYPE}"

script:
  - ctest -M Experimental -T Start -T Build -T Test -T Submit
  - make all --keep-going && make check # If ctest built the project unsuccessfully, `make all && make check` will report errors to Travis

