language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

cache:
  apt: true

notifications:
  email: false

branches:
  only:
    - master
    - develop
    - /^.*travis.*$/

env:
  matrix:
    - USE_LLVM=Off
    - USE_LLVM=On

before_install:
  - ./.travis/${TRAVIS_OS_NAME}/install-dependencies.sh

before_script:
  - mkdir -p build
  - cd build
  - cmake . -DUSE_LLVM=$USE_LLVM -DBUILD_TESTS=On -DCMAKE_BUILD_TYPE=Release -DSITE="${TRAVIS_OS_NAME}@Travis" -DBUILDNAME="${TRAVIS_BRANCH}_${CMAKE_CXX_COMPILER}"

script:
  - cd build
  - make ExperimentalBuild
  - make ExperimentalTest

after_script:
  - cd build
  - make ExperimentalSubmit

